[package]
name = "tag"
version = "0.0.1"
authors = ["Jared S. Candelaria <jsc+tag@demigods.org>"]

[dependencies]
pest = "1.0"
pest_derive = "1.0"
failure = "0.1.2"
failure_derive = "0.1.2"
serde = "^1.0.27"
bincode = "1.0.1"
serde_derive = "^1.0.27"
